<?php

class MT_Giftcard_Block_Adminhtml_Catalog_Product_Edit_Tabs_Giftcard_Form
    extends Mage_Adminhtml_Block_Widget_Form
{

    protected function _prepareForm()
    {
        $helper = Mage::helper('giftcard');
        $data = array();
        if (Mage::registry('giftcard_data'))
            $data = Mage::registry('giftcard_data')->getData();

        $form = new Varien_Data_Form();
        $this->setForm($form);
        $fieldset = $form->addFieldset('general', array('legend' => Mage::helper('giftcard')->__('Gift Cards')));

        $fieldset->addField('gift_card_series', 'select', array(
            'label' => Mage::helper('giftcard')->__('Gift Card Series'),
            'class' => 'required-entry',
            'required' => true,
            'name' => 'status',
            'values' => Mage::getModel('giftcard/series')->getOptionArray(),
            'after_element_html' => '<br/><small>'.$helper->__('Gift Cards will be generated by this rule').'</small>',
        ));

        $form->setValues($data);

        return parent::_prepareForm();
    }


}