<table id="creditmemo_gift_card">
    <tr>
        <td>
            <label class="normal" for="refund_gift_card"><?php echo $this->__('Refund to Gift Card')?></label>
        </td>
        <td>
            <input id="refund_gift_card" class="input-text not-negative-amount" type="text" value="<?php echo $this->getGiftCardRefundTotal();?>" name="creditmemo[refund_gift_card]"/></td>
    </tr>
</table>