<?php if ($this->isActive()): ?>

<?php $formVisible = $this->isFormVisible();?>

<ul class="form-list">
    <li class="control"> <input <?php if ($formVisible): ?>checked="checked"<?php endif;?> id="p_method_gift_card" class="checkbox" type="checkbox" onclick="payment.switchMethod('cashondelivery')" title="<?php echo $this->__('Use Gift Card to check out');?>" name="apply_gift_card" value="1"/>
        <label for="p_method_gift_card"><?php echo $this->__('Use Gift Card to check out');?></label>
    </li>

    <?php $giftCardCollection = $this->getAppliedGiftCardCollection();?>
    <?php if (count($giftCardCollection) > 0): ?>
        <?php foreach ($giftCardCollection as $key => $giftCard): ?>
            <li class="control gc-form-element">
                <input id="gift_card_code_<?php echo $key;?>" checked="checked" class="checkbox" type="checkbox" title="<?php echo $this->__('Use Gift Card to check out');?>" name="apply_gift_card[]" value="<?php echo $giftCard->getCode();?>"/>
                <label for="gift_card_code_<?php echo $key;?>"><?php echo $this->__('Gift Card');?> (<?php echo $giftCard->getCode();?>) <?php echo $this->__('Balance: ');?><strong><?php echo $giftCard->getFormatedBalance();?></strong></label>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
    <li id="gc-cart-form" class="scaffold-form gc-form-element" <?php if (!$formVisible): ?>style="display: none"<?php endif; ?>>
        <div class="fieldset">
            <ul>
                <li class="fields">
                    <div class="customer-name">
                        <div class="field name-firstname">
                            <label for="gift_card_code"><?php echo $this->__('Enter Gift Card Code');?></label>
                            <div class="input-box">
                                <input id="gift_card_code" class="input-text" type="text"  title="<?php echo $this->__('Gift Card Code');?>" value="" name="giftcard_code">
                            </div>
                            <div class="gc-cart-action">
                                <div class="button-box">
                                    <button type="button" title="<?php echo $this->__('Apply Gift Card') ?>" class="button" onclick="GiftCardCheckout.addGiftCardCodeSubmit()"><span><span><?php echo $this->__('Apply Gift Card') ?></span></span></button>
                                </div>
                                <div id="gc-please-wait" class="please-wait">
                                    <img class="v-middle" title="Loading next step..." alt="Loading next step..." src="<?php echo $this->getSkinUrl('images/mt/giftcard/opc-ajax-loader.gif') ?>">
                                    <?php echo $this->__('Please wait...'); ?>
                                </div>
                                <?php if ($error = $this->getError()): ?>
                                <div id="gc-applied-codes-error"><?php echo $error;?></div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </li>
</ul>

<?php endif; ?>