<?php $giftCards = $this->getGiftCardArray();  ?>
<?php if (count($giftCards) != 0): ?>
    <?php foreach ($giftCards as $giftCard): ?>
        <?php  $giftCardObj = $giftCard['source']; ?>
        <tr>
            <td class="label">
                <?php echo $this->__('Refund to Gift Card (%s)', $giftCard['code']) ?></td>
            <td><input type="text" name="gift_card[<?php echo $giftCardObj->getId()?>]" value="<?php echo $giftCard['total']?>" class="input-text not-negative-amount" style="width:60px;text-align:right" id="shipping_amount" /></td>
        </tr>
        <tr>
            <td colspan="2"></td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
